version: '3.4'

services:
  pizzeriaapi:
    image: ${DOCKER_REGISTRY-}pizzeriaapi
    build:
      context: .
      dockerfile: PizzeriaAPI/Dockerfile
    environment:
       "ASPNETCORE_Kestrel__Certificates__Default__Password": "StrongPassword123!"
       "ASPNETCORE_Kestrel__Certificates__Default__Path": "../https/aspnetapp.pfx"
    ports:
       - "7100:8080"
       - "7101:8081"
    restart: 
        always
    volumes:
        - ~/.aspnet/https:/https
    depends_on:
      - mssql

  mssql:
    container_name: sql-server-pizzeriaapi
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=StrongPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"

  seq:
    image:  datalust/seq:latest
    container_name: seq-pazzeriaapi
    environment:
    - ACCEPT_EULA=Y
    ports:
    - 5341:5341
    - 8081:80

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    container_name: redis