// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzeria.Domain;

#nullable disable

namespace Pizzeria.Domain.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20240330163823_ChangeInventoryIngredientRelation")]
    partial class ChangeInventoryIngredientRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pizzeria.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("city");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("zipcode");

                    b.HasKey("AddressId");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(55)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .HasMaxLength(55)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_number")
                        .IsFixedLength();

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Ingredient", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("ingredient_name");

                    b.Property<decimal>("IngredientPrice")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("ingredient_price");

                    b.Property<string>("IngredientWeightMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("ingredient_weight_measure");

                    b.HasKey("IngredientId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Inventory", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("IngredientId");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("item_name");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("item_price");

                    b.Property<string>("ItemSize")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("item_size");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.HasKey("ItemId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<bool>("Delivery")
                        .HasColumnType("bit")
                        .HasColumnName("delivery");

                    b.Property<Guid?>("DeliveryAddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("delivery_address_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_id");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("StaffId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Recipe", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<TimeOnly>("CookingTime")
                        .HasColumnType("time")
                        .HasColumnName("cooking_time");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("recipe_name");

                    b.HasKey("RecipeId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("IngredientWeight")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_weight");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Staff", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("position");

                    b.HasKey("StaffId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Ingredient", b =>
                {
                    b.HasOne("Pizzeria.Domain.Models.Inventory", "Inventory")
                        .WithOne("Ingredient")
                        .HasForeignKey("Pizzeria.Domain.Models.Ingredient", "IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_inventory_ingredients");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Item", b =>
                {
                    b.HasOne("Pizzeria.Domain.Models.Recipe", "ItemNavigation")
                        .WithOne("Item")
                        .HasForeignKey("Pizzeria.Domain.Models.Item", "ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_items_recipes");

                    b.Navigation("ItemNavigation");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Order", b =>
                {
                    b.HasOne("Pizzeria.Domain.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_orders_customers");

                    b.HasOne("Pizzeria.Domain.Models.Address", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .HasConstraintName("FK_orders_address");

                    b.HasOne("Pizzeria.Domain.Models.Staff", "Staff")
                        .WithMany("Orders")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_staff");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("Pizzeria.Domain.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_order_items_items");

                    b.HasOne("Pizzeria.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_order_items_orders");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Pizzeria.Domain.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_recipe_ingredients_ingredients");

                    b.HasOne("Pizzeria.Domain.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_recipe_ingredients_recipes");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Inventory", b =>
                {
                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Recipe", b =>
                {
                    b.Navigation("Item");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Pizzeria.Domain.Models.Staff", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
